version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"
    command: redis-server --requirepass G0rDkQtRcl!E --appendonly yes
    volumes:
      - "./redis/data:/app"
